### ISSUE TITLE
Move as much functionality into classes as possible

### ISSUE THREAD

**Issue by aab29** [helloGov/singleAction#10]
For the prototype we kind of just wrote global functions and put them wherever we thought was convenient.  🏪  That made sense, but if this app is going to grow much larger, I think we should make sure we're doing our best to stick to object-oriented principles and whatnot.  🎒  I'd say it's fine to have a global function or two in the app's initialization code.  🌱  Or if there are other conventions in web development where we do things outside of objects, it's fine to conform to them.  ✌️  But aside from that, I'd definitely vote to move as much code as possible into classes with clearly-defined responsibilities.  🚀

**Comment by WCRest** [comment]
I'm with you on this, @aab29 

I've tried to move a lot of routing and controller logic out of the main server file into their own classes. I've tried to use that file, /index.js, only for configuring the express server. 

I also agree that 1.2 seems the most practical. I've been creating classes as object literals, approach 2, but if I'm reading the article you linked correctly, this practice "makes no sense" 😂
