### ISSUE TITLE
Influencer sign up page backend

### ISSUE THREAD

**Issue by WCRest** [helloGov/singleAction#13]
Accept POST requests to /signup endpoint. Create a new object in db.influencers collection that stores:

- Full name
- Image
- Bio
- login name
- password

Upon successful sign-up, forward to account page/ list of campaigns.

If duplicate login name exists, return to sign up page with error message.

**Comment by Dfenestrator** [comment]
Just leaving one task open on the frontend.

**Comment by Dfenestrator** [comment]
We do need to handle the error case here for existing signup names.
