### ISSUE TITLE
Center logo on nav bar

### ISSUE THREAD

**Issue by rachelcolby11** [helloGov/singleAction#62]
Logo is currently slightly off-center:

![image](https://cloud.githubusercontent.com/assets/10647307/22852715/43b05d2a-eff7-11e6-999e-d77a48749c6c.png)

**Comment by Dfenestrator** [comment]
Do we have a good way of testing this on mobile?

**Comment by rachelcolby11** [comment]
I've been using the device simulator on Chrome dev tools to get a sense of how it looks. The off-center thing is more obvious on desktop than on mobile though. The way the bar was done at the hackathon was kind of a hacky approach using different size bootstrap columns, it wasn't really "centered" per se

**Comment by rachelcolby11** [comment]
Addressed with PR #70
